listeners:
    - bima:listener:filter:elasticsearch
    - bima:listener:create:elasticsearch
    - bima:listener:update:elasticsearch
    - bima:listener:delete:elasticsearch
    - bima:listener:create:created_by
    - bima:listener:update:updated_by
    - bima:listener:delete:deleted_by
